# To separate your traces from other application
langsmith_project: vmcore-analysis-agent
langsmith_tracing: false

## LLM choice:
thinking: "enabled" # enabled or disabled
llm_model: deepseek-v4-pro #
reasoning_effort: "max" # high
base_url: https://api.deepseek.com
temperature: 0.1
