# To separate your traces from other application
LANGSMITH_PROJECT: vmcore-analysis-agent
LANGSMITH_TRACING: true
LANGSMITH_API_KEY: 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

## LLM choice:
DEEPSEEK_API_KEY: sk-b5480f840a794c69a0af1732459f3ae4
# LLM_MODEL: deepseek-chat
LLM_MODEL: deepseek-reasoner
BASE_URL: https://api.deepseek.com
TEMPERATURE: 0.1
